name: deploy site to server

on:
    push:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            -   name: clone repo
                uses: actions/checkout@v4

            -   name: install bun packet managet
                uses: oven-sh/setup-bun@v2
                with:
                  bun-version-file: ".bun-version"
            
            -   name: install astro packages
                run: bun install
            
            -   name: check errors
                run: bun run astro check
            
            -   name: checkout repository owner URL
                run: echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY_OWNER"   

    deploy:
        needs: check
        runs-on: ubuntu-latest

        steps:
            -   name: clone repo
                uses: actions/checkout@v4

            -   name: install bun packet managet
                uses: oven-sh/setup-bun@v2
                with:
                  bun-version-file: ".bun-version"
            
            -   name: install astro packages
                run: bun install
            
            -   name: generate build
                run: bun run build
            
            -   name: copy to server
                uses: burnett01/rsync-deployments@master

                with:
                    switches: -avzr --delete
                    path: dist/
                    remote_path: /root/critical.su/dist
                    remote_host: ${{ secrets.SSH_HOST }}
                    remote_user: ${{ secrets.SSH_USER }}
                    remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
            
            -   name: reload site on server via ssh
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        pm2 restart critical.su